twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
knp_paginator:
    page_range: 5
    default_options:
        page_name: page                
        sort_field_name: sort          
        sort_direction_name: direction 
        distinct: true                 
        filter_field_name: filterField 
        filter_value_name: filterValue 
    template:
        pagination: '@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig'
        sortable: '@KnpPaginator/Pagination/twitter_bootstrap_v3_sortable_link.html.twig' 
        filtration: '@KnpPaginator/Pagination/filtration.html.twig'  
